/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDocs {
    }
    interface AppHome {
    }
    interface AppIndexes {
    }
    interface AppLoad {
    }
    interface AppManagePermission {
    }
    interface AppNewService {
    }
    interface AppServiceList {
    }
    interface WcElixirGa4ghService {
    }
    interface WcElixirUtilsManagePermissions {
        "authToken": string;
        "itemsPerPage"?: number;
    }
    interface WcElixirUtilsNewService {
    }
    interface WcElixirUtilsServiceList {
        "authToken": string;
        "itemsPerPage"?: number;
    }
}
declare global {
    interface HTMLAppDocsElement extends Components.AppDocs, HTMLStencilElement {
    }
    var HTMLAppDocsElement: {
        prototype: HTMLAppDocsElement;
        new (): HTMLAppDocsElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppIndexesElement extends Components.AppIndexes, HTMLStencilElement {
    }
    var HTMLAppIndexesElement: {
        prototype: HTMLAppIndexesElement;
        new (): HTMLAppIndexesElement;
    };
    interface HTMLAppLoadElement extends Components.AppLoad, HTMLStencilElement {
    }
    var HTMLAppLoadElement: {
        prototype: HTMLAppLoadElement;
        new (): HTMLAppLoadElement;
    };
    interface HTMLAppManagePermissionElement extends Components.AppManagePermission, HTMLStencilElement {
    }
    var HTMLAppManagePermissionElement: {
        prototype: HTMLAppManagePermissionElement;
        new (): HTMLAppManagePermissionElement;
    };
    interface HTMLAppNewServiceElement extends Components.AppNewService, HTMLStencilElement {
    }
    var HTMLAppNewServiceElement: {
        prototype: HTMLAppNewServiceElement;
        new (): HTMLAppNewServiceElement;
    };
    interface HTMLAppServiceListElement extends Components.AppServiceList, HTMLStencilElement {
    }
    var HTMLAppServiceListElement: {
        prototype: HTMLAppServiceListElement;
        new (): HTMLAppServiceListElement;
    };
    interface HTMLWcElixirGa4ghServiceElement extends Components.WcElixirGa4ghService, HTMLStencilElement {
    }
    var HTMLWcElixirGa4ghServiceElement: {
        prototype: HTMLWcElixirGa4ghServiceElement;
        new (): HTMLWcElixirGa4ghServiceElement;
    };
    interface HTMLWcElixirUtilsManagePermissionsElement extends Components.WcElixirUtilsManagePermissions, HTMLStencilElement {
    }
    var HTMLWcElixirUtilsManagePermissionsElement: {
        prototype: HTMLWcElixirUtilsManagePermissionsElement;
        new (): HTMLWcElixirUtilsManagePermissionsElement;
    };
    interface HTMLWcElixirUtilsNewServiceElement extends Components.WcElixirUtilsNewService, HTMLStencilElement {
    }
    var HTMLWcElixirUtilsNewServiceElement: {
        prototype: HTMLWcElixirUtilsNewServiceElement;
        new (): HTMLWcElixirUtilsNewServiceElement;
    };
    interface HTMLWcElixirUtilsServiceListElement extends Components.WcElixirUtilsServiceList, HTMLStencilElement {
    }
    var HTMLWcElixirUtilsServiceListElement: {
        prototype: HTMLWcElixirUtilsServiceListElement;
        new (): HTMLWcElixirUtilsServiceListElement;
    };
    interface HTMLElementTagNameMap {
        "app-docs": HTMLAppDocsElement;
        "app-home": HTMLAppHomeElement;
        "app-indexes": HTMLAppIndexesElement;
        "app-load": HTMLAppLoadElement;
        "app-manage-permission": HTMLAppManagePermissionElement;
        "app-new-service": HTMLAppNewServiceElement;
        "app-service-list": HTMLAppServiceListElement;
        "wc-elixir-ga4gh-service": HTMLWcElixirGa4ghServiceElement;
        "wc-elixir-utils-manage-permissions": HTMLWcElixirUtilsManagePermissionsElement;
        "wc-elixir-utils-new-service": HTMLWcElixirUtilsNewServiceElement;
        "wc-elixir-utils-service-list": HTMLWcElixirUtilsServiceListElement;
    }
}
declare namespace LocalJSX {
    interface AppDocs {
    }
    interface AppHome {
    }
    interface AppIndexes {
    }
    interface AppLoad {
    }
    interface AppManagePermission {
    }
    interface AppNewService {
    }
    interface AppServiceList {
    }
    interface WcElixirGa4ghService {
    }
    interface WcElixirUtilsManagePermissions {
        "authToken"?: string;
        "itemsPerPage"?: number;
    }
    interface WcElixirUtilsNewService {
    }
    interface WcElixirUtilsServiceList {
        "authToken"?: string;
        "itemsPerPage"?: number;
    }
    interface IntrinsicElements {
        "app-docs": AppDocs;
        "app-home": AppHome;
        "app-indexes": AppIndexes;
        "app-load": AppLoad;
        "app-manage-permission": AppManagePermission;
        "app-new-service": AppNewService;
        "app-service-list": AppServiceList;
        "wc-elixir-ga4gh-service": WcElixirGa4ghService;
        "wc-elixir-utils-manage-permissions": WcElixirUtilsManagePermissions;
        "wc-elixir-utils-new-service": WcElixirUtilsNewService;
        "wc-elixir-utils-service-list": WcElixirUtilsServiceList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-docs": LocalJSX.AppDocs & JSXBase.HTMLAttributes<HTMLAppDocsElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-indexes": LocalJSX.AppIndexes & JSXBase.HTMLAttributes<HTMLAppIndexesElement>;
            "app-load": LocalJSX.AppLoad & JSXBase.HTMLAttributes<HTMLAppLoadElement>;
            "app-manage-permission": LocalJSX.AppManagePermission & JSXBase.HTMLAttributes<HTMLAppManagePermissionElement>;
            "app-new-service": LocalJSX.AppNewService & JSXBase.HTMLAttributes<HTMLAppNewServiceElement>;
            "app-service-list": LocalJSX.AppServiceList & JSXBase.HTMLAttributes<HTMLAppServiceListElement>;
            "wc-elixir-ga4gh-service": LocalJSX.WcElixirGa4ghService & JSXBase.HTMLAttributes<HTMLWcElixirGa4ghServiceElement>;
            "wc-elixir-utils-manage-permissions": LocalJSX.WcElixirUtilsManagePermissions & JSXBase.HTMLAttributes<HTMLWcElixirUtilsManagePermissionsElement>;
            "wc-elixir-utils-new-service": LocalJSX.WcElixirUtilsNewService & JSXBase.HTMLAttributes<HTMLWcElixirUtilsNewServiceElement>;
            "wc-elixir-utils-service-list": LocalJSX.WcElixirUtilsServiceList & JSXBase.HTMLAttributes<HTMLWcElixirUtilsServiceListElement>;
        }
    }
}
