/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestWc {
    }
}
declare global {
    interface HTMLTestWcElement extends Components.TestWc, HTMLStencilElement {
    }
    var HTMLTestWcElement: {
        prototype: HTMLTestWcElement;
        new (): HTMLTestWcElement;
    };
    interface HTMLElementTagNameMap {
        "test-wc": HTMLTestWcElement;
    }
}
declare namespace LocalJSX {
    interface TestWc {
    }
    interface IntrinsicElements {
        "test-wc": TestWc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-wc": LocalJSX.TestWc & JSXBase.HTMLAttributes<HTMLTestWcElement>;
        }
    }
}
